name: Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "unreleased" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Test
      run: dotnet test -c Release --no-build
